# Generated by Django 5.0.1 on 2024-02-02 09:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_oredritem_oreder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oreder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Oredritem',
            new_name='Orderitem',
        ),
    ]
