# Generated by Django 5.0.1 on 2024-02-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_checkoutaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='Zip_code',
            field=models.CharField(max_length=12),
        ),
    ]
