# Generated by Django 4.2.3 on 2024-02-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_checkoutaddress_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutaddress',
            old_name='Zip_code',
            new_name='zip_code',
        ),
    ]
