# Generated by Django 4.2.3 on 2024-02-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_zip_code_checkoutaddress_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='apartment_address',
        ),
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='zip_code',
        ),
    ]
