# Generated by Django 4.2.3 on 2024-02-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_checkoutaddress_apartment_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutAddress',
        ),
    ]
